
title: Moving the U.S. Government Towards Zero Trust Cybersecurity Principles
email: zerotrust@omb.eop.gov
description: >- # this means to ignore newlines until "baseurl:"
  Read and comment on the U.S. government's draft Federal Zero Trust Strategy. This strategy is intended to accelerate federal agencies towards a shared baseline of early zero trust maturity.
baseurl: "" # the subpath of your site, e.g. /blog

# Twitter handle. Only the handle, not the URL.
twitter: OMBPress

dap:
  agency: EOP
  subagency: OMB

# Site Navigation
primary_navigation:
  - name: Home
    url: /
  - name: Federal Zero Trust Strategy
    url: /federal-zero-trust-strategy/
  - name: Zero Trust Maturity Model
    url: /zero-trust-maturity-model/
  - name: Cloud Security Technical Reference Architecture
    url: /cloud-security-technical-reference-architecture/


secondary_navigation:
  - name: Executive Order 14028
    url: "https://www.whitehouse.gov/briefing-room/presidential-actions/2021/05/12/executive-order-on-improving-the-nations-cybersecurity/"
  - name: WhiteHouse.gov
    url: "https://www.whitehouse.gov"



collections:
  pages:
    output: true
    permalink: /:path/

permalink: pretty

# markdown: kramdown
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap # See additional instructions for url parameter above.
  - jekyll-seo-tag


exclude:
  - package.json
  - package-lock.json
  - README.md
  - CONTRIBUTING.md
  - LICENSE.md
  - degit.json
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - todo.txt

# My apologies for this hack - I converted this from a Federalist-oriented
# build system to a GitHub Pages-oriented build system.
sass:
  sass_dir: assets/uswds/scss
